# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
jobs:
 - job: 'flask_basic'

   pool:
    vmImage: 'Ubuntu-16.04'
  
   strategy:
    matrix:
      Python36:
        python.version: "3.6"
      Python37:
        python.version: "3.7"
    maxParallel: 2

   steps:
   - task: CmdLine@2
     inputs:
       script: 'dir'

   - task: UsePythonVersion@0
     inputs:
      versionSpec: '$(python.version)'

   - script: |
      python -m pip install --upgrade pip
      python pip install Click
      python pip install Flask
      python pip install Jinja2
      
      python pip install psutil
      python pip install setuptools
      python pip install xmlrunner
      
      cd venv
      python app-test.py
     displayName: 'Run Tests'

   - task: PublishTestResults@2
     inputs:
       testResultsFiles: 'test-reports/'
       testRunTitle: '$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)] - Python $(python.version)'
     condition: succeededOrFailed()
     

