# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
jobs:
 - job: 'flask_basic'

   pool:
    vmImage: 'Ubuntu-16.04'
  
   strategy:
    matrix:
      Python36:
        python.version: "3.6"
      Python37:
        python.version: "3.7"
    maxParallel: 2

   steps:
   - task: CmdLine@2
     inputs:
       script: 'dir'

   - task: UsePythonVersion@0
     inputs:
      versionSpec: '$(python.version)'

   - script: |
      python -m pip install --upgrade pip
      python -m pip install Click
      python -m pip install Flask
      python -m pip install Jinja2
      python -m pip install MarkupSafe
      python -m pip install Werkzeug
      python -m pip install itsdangerous
      python -m pip install psutil
      python -m pip install setuptools
      python -m pip install xmlrunner
      
      cd venv

      python app.py &
      python app-test.py
      
     displayName: 'Run Functional Tests'

   - task: PublishTestResults@2
     inputs:
       testResultsFiles: 'test-reports/results.xml'
       testRunTitle: '$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)] - Python $(python.version)'
     condition: succeededOrFailed()
     

